import {
  CalenderIcons,
  DashbordIcons,
  DealsIcons,
  EmailIcons,
  LeadIcons,
  ProjectsIcons,
  ResoursesIcons,
  SettingIcons,
} from "./Icons";

export const CustomerRelation = [
  {
    icon: <DashbordIcons />,
    name: "Contact",
  },
  {
    icon: <DealsIcons />,
    name: "Deals",
  },
  {
    icon: <LeadIcons />,
    name: "Lead Capture",
  },
  {
    icon: <CalenderIcons />,
    name: "Callender",
  },
  {
    icon: <ProjectsIcons />,
    name: "Projects",
  },
  {
    icon: <ResoursesIcons />,
    name: "Resourses",
  },
  {
    icon: <SettingIcons />,
    name: "Setting",
  },
];
export const tabelData = [
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Floyd Miles",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Inactive",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    width: "71px",
    emailicon: <EmailIcons />,
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Floyd Miles",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    status: "Inactive",
    width: "71px",
    emailicon: <EmailIcons />,
  },
  {
    name: "Floyd Miles",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Jane Cooper",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Inactive",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    width: "71px",
    emailicon: <EmailIcons />,
  },
  {
    name: "Jane Cooper",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Customer Name1",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    status: "Inactive",
    width: "71px",
    emailicon: <EmailIcons />,
  },
  {
    name: "Customer Name1",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Customer Name1",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Inactive",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    width: "71px",
    emailicon: <EmailIcons />,
  },
  {
    name: "Customer Name1",
    company: "Microsoft",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Active",
    emailicon: <EmailIcons />,
  },
  {
    name: "Customer Name1",
    company: "Yahoo",
    phoneno: "(225) 555-0118",
    contact: "jane@microsoft.com",
    source: "None",
    status: "Inactive",
    color: "#FE566B",
    bgcolor: "#FFECEF",
    width: "71px",
    emailicon: <EmailIcons />,
  },
];
